// Auto-generated by Helix Architect (consolidate mode).
// Winner of experiment exp_search_relevance_2025: semantic_v2.
// Lift: +1.7pp en search->purchase rate, p(best > control) = 0.992.
// AB test corrió 14 días con 7548 sesiones; sin breach de latencia.

import { embed } from "@/lib/embeddings/sbert";
import { cosineSimilarity } from "@/lib/math";
import type { SearchHit } from "@/lib/search/types";

export async function semanticRerank(
  query: string,
  hits: SearchHit[]
): Promise<SearchHit[]> {
  const queryVec = await embed(query);
  const scored = await Promise.all(
    hits.map(async (hit) => ({
      hit,
      score: cosineSimilarity(queryVec, await embed(hit.title)),
    }))
  );
  return scored
    .sort((a, b) => b.score - a.score)
    .map((x) => x.hit);
}
